<a href="https://colab.research.google.com/github/demolakstate/bumble_bees_detection/blob/main/results_sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### natvigi vs cockerelli ###

              precision    recall  f1-score   support

         0.0       0.50      0.50      0.50         4
         1.0       0.50      0.50      0.50         4

    accuracy                           0.50         8
  




### polaris vs variabilis ###

tf.Tensor(
  [[ 8 12]
  
            [11  9]],



              precision    recall  f1-score   support

         0.0       0.42      0.40      0.41        20
         1.0       0.43      0.45      0.44        20

    accuracy                           0.42        40



### B. occidentalis vs B. appositus ###

tf.Tensor(
[[442 558]
 [441 559]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.50      0.44      0.47      1000
         1.0       0.50      0.56      0.53      1000

    accuracy                           0.50      2000
   macro avg       0.50      0.50      0.50      2000
weighted avg       0.50      0.50      0.50      2000



tf.Tensor(
[[455 319]
 [401 373]], shape=(2, 2), dtype=int32)
              precision    recall  f1-score   support

         0.0       0.53      0.59      0.56       774
         1.0       0.54      0.48      0.51       774

    accuracy                           0.53      1548
   macro avg       0.54      0.53      0.53      1548
weighted avg       0.54      0.53      0.53      1548



## B. cryptarum vs B. fraternus ##

tf.Tensor(
[[610 226]
 [208 628]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.75      0.73      0.74       836
         1.0       0.74      0.75      0.74       836

    accuracy                           0.74      1672
   macro avg       0.74      0.74      0.74      1672
weighted avg       0.74      0.74      0.74      1672



## B. caliginosus vs B. frigidus ##

tf.Tensor(
[[140 152]
 [ 85 207]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.62      0.48      0.54       292
         1.0       0.58      0.71      0.64       292

    accuracy                           0.59       584
   macro avg       0.60      0.59      0.59       584
weighted avg       0.60      0.59      0.59       584

