<a href="https://colab.research.google.com/github/demolakstate/bumble_bees_detection/blob/main/results_sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### natvigi vs cockerelli ###

              precision    recall  f1-score   support

         0.0       0.50      0.50      0.50         4
         1.0       0.50      0.50      0.50         4

    accuracy                           0.50         8
  




### polaris vs variabilis ###

tf.Tensor(
  [[ 8 12]
  
            [11  9]],



              precision    recall  f1-score   support

         0.0       0.42      0.40      0.41        20
         1.0       0.43      0.45      0.44        20

    accuracy                           0.42        40



### B. occidentalis vs B. appositus ###

tf.Tensor(
[[442 558]
 [441 559]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.50      0.44      0.47      1000
         1.0       0.50      0.56      0.53      1000

    accuracy                           0.50      2000
   macro avg       0.50      0.50      0.50      2000
weighted avg       0.50      0.50      0.50      2000



tf.Tensor(
[[455 319]
 [401 373]], shape=(2, 2), dtype=int32)
              precision    recall  f1-score   support

         0.0       0.53      0.59      0.56       774
         1.0       0.54      0.48      0.51       774

    accuracy                           0.53      1548
   macro avg       0.54      0.53      0.53      1548
weighted avg       0.54      0.53      0.53      1548



## B. cryptarum vs B. fraternus ##

tf.Tensor(
[[610 226]
 [208 628]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.75      0.73      0.74       836
         1.0       0.74      0.75      0.74       836

    accuracy                           0.74      1672
   macro avg       0.74      0.74      0.74      1672
weighted avg       0.74      0.74      0.74      1672



## B. caliginosus vs B. frigidus ##

tf.Tensor(
[[140 152]
 [ 85 207]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.62      0.48      0.54       292
         1.0       0.58      0.71      0.64       292

    accuracy                           0.59       584
   macro avg       0.60      0.59      0.59       584
weighted avg       0.60      0.59      0.59       584



## B. cryptarum vs B. natvigi ##

tf.Tensor(
[[2 2]
 [1 3]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.67      0.50      0.57         4
         1.0       0.60      0.75      0.67         4

    accuracy                           0.62         8
   macro avg       0.63      0.62      0.62         8
weighted avg       0.63      0.62      0.62         8



## Bombus_cryptarum vs Bombus_variabilis ##

tf.Tensor(
[[ 8 14]
 [ 8 14]], shape=(2, 2), dtype=int32)

 
              precision    recall  f1-score   support

         0.0       0.50      0.36      0.42        22
         1.0       0.50      0.64      0.56        22

    accuracy                           0.50        44
   macro avg       0.50      0.50      0.49        44
weighted avg       0.50      0.50      0.49        44


## Bombus_cryptarum vs Bombus_appositus ##

tf.Tensor(
[[408 428]
 [404 432]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.50      0.49      0.50       836
         1.0       0.50      0.52      0.51       836

    accuracy                           0.50      1672
   macro avg       0.50      0.50      0.50      1672
weighted avg       0.50      0.50      0.50      1672



## Bombus_cryptarum vs Bombus_frigidus ##

tf.Tensor(
[[224 132]
 [172 184]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.57      0.63      0.60       356
         1.0       0.58      0.52      0.55       356

    accuracy                           0.57       712
   macro avg       0.57      0.57      0.57       712
weighted avg       0.57      0.57      0.57       712


## Bombus_fraternus vs Bombus_cockerelli ##

tf.Tensor(
[[4 0]
 [0 4]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         4
         1.0       1.00      1.00      1.00         4

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8

## Bombus_fraternus vs Bombus_polaris ##

tf.Tensor(
[[16  4]
 [ 7 13]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.70      0.80      0.74        20
         1.0       0.76      0.65      0.70        20

    accuracy                           0.73        40
   macro avg       0.73      0.73      0.72        40
weighted avg       0.73      0.72      0.72        40



## Bombus_fraternus vs Bombus_occidentalis ##

tf.Tensor(
[[508 338]
 [334 512]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.60      0.60      0.60       846
         1.0       0.60      0.61      0.60       846

    accuracy                           0.60      1692
   macro avg       0.60      0.60      0.60      1692
weighted avg       0.60      0.60      0.60      1692


## Bombus_fraternus vs Bombus_caliginosus ##

tf.Tensor(
[[154 138]
 [ 96 196]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.62      0.53      0.57       292
         1.0       0.59      0.67      0.63       292

    accuracy                           0.60       584
   macro avg       0.60      0.60      0.60       584
weighted avg       0.60      0.60      0.60       584


## Bombus_cockerelli vs Bombus_variabilis ##

tf.Tensor(
[[4 0]
 [1 3]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.80      1.00      0.89         4
         1.0       1.00      0.75      0.86         4

    accuracy                           0.88         8
   macro avg       0.90      0.88      0.87         8
weighted avg       0.90      0.88      0.87         8



## Bombus_cockerelli vs Bombus_appositus ##

tf.Tensor(
[[0 4]
 [1 3]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         4
         1.0       0.43      0.75      0.55         4

    accuracy                           0.38         8
   macro avg       0.21      0.38      0.27         8
weighted avg       0.21      0.38      0.27         8
